// @ts-nocheck
export const GLOBAL_FIAT_CURRENCIES = [
  'USD','CAD','EUR','GBP','AUD','NZD','JPY','CNY','HKD','SGD','INR','AED','SAR','QAR','KWD','BHD','OMR','CHF','SEK','NOK','DKK','PLN','CZK','HUF','RON','BGN','TRY','UAH','ILS','ZAR','NGN','KES','GHS','MAD','EGP','MXN','BRL','ARS','CLP','COP','PEN','UYU'
];

export const CRYPTO_CURRENCIES = [
  'TON','TELEGRAM_STARS','USDT','USDC','BTC','ETH','BNB','SOL','XRP','ADA','DOGE','TRX','MATIC','LTC','DOT','AVAX','LINK','XLM','BCH','XMR'
];

export const ALL_MARKET_CURRENCIES = [...GLOBAL_FIAT_CURRENCIES, ...CRYPTO_CURRENCIES];

export const DEFAULT_PRICE_OPTIONS = ['USD', 'CAD', 'TON', 'TELEGRAM_STARS', 'USDT', 'BTC'];