// @ts-nocheck
export const DEMO_BOTS = [
  { bot_id: 'L-001', name: 'Atlas', role: 'leader bot', farm_group: 'command', specialty: 'command_support', level: 8, efficiency: 94, integrity: 93, confidence: 92, fatigue: 18, load: 38, uptime: 99, maintenance_status: 'healthy', output_quality: 91, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 92, coordination_efficiency: 95, max_concurrent_tasks: 3, system_health: 96 },
  { bot_id: 'C-101', name: 'Northstar', role: 'commander bot', farm_group: 'operations', specialty: 'analysis', level: 6, efficiency: 88, integrity: 89, confidence: 87, fatigue: 28, load: 52, uptime: 97, maintenance_status: 'healthy', output_quality: 84, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 84, coordination_efficiency: 88, max_concurrent_tasks: 2, system_health: 90 },
  { bot_id: 'C-102', name: 'Signal', role: 'commander bot', farm_group: 'research', specialty: 'research', level: 6, efficiency: 86, integrity: 88, confidence: 85, fatigue: 31, load: 49, uptime: 96, maintenance_status: 'healthy', output_quality: 83, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 82, coordination_efficiency: 87, max_concurrent_tasks: 2, system_health: 89 },
  { bot_id: 'S-201', name: 'Shield One', role: 'security bot', farm_group: 'security', specialty: 'security', level: 6, efficiency: 85, integrity: 95, confidence: 91, fatigue: 22, load: 36, uptime: 99, maintenance_status: 'healthy', output_quality: 86, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 83, coordination_efficiency: 88, max_concurrent_tasks: 2, system_health: 94 },
  { bot_id: 'S-202', name: 'Shield Two', role: 'security bot', farm_group: 'security', specialty: 'verification', level: 5, efficiency: 84, integrity: 94, confidence: 90, fatigue: 24, load: 34, uptime: 99, maintenance_status: 'healthy', output_quality: 85, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 81, coordination_efficiency: 86, max_concurrent_tasks: 2, system_health: 93 },
  { bot_id: 'T-301', name: 'Harbor', role: 'task bot', farm_group: 'operations', specialty: 'data_gathering', level: 4, efficiency: 84, integrity: 87, confidence: 80, fatigue: 26, load: 42, uptime: 97, maintenance_status: 'healthy', output_quality: 79, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 75, coordination_efficiency: 78, max_concurrent_tasks: 1, system_health: 86 },
  { bot_id: 'T-302', name: 'Prism', role: 'task bot', farm_group: 'operations', specialty: 'analysis', level: 5, efficiency: 91, integrity: 89, confidence: 90, fatigue: 33, load: 61, uptime: 97, maintenance_status: 'healthy', output_quality: 88, risk_level: 'low', communication_status: 'clear', status: 'assigned', bandwidth: 86, coordination_efficiency: 84, max_concurrent_tasks: 2, system_health: 90 },
  { bot_id: 'T-303', name: 'Relay', role: 'task bot', farm_group: 'support', specialty: 'communications', level: 3, efficiency: 72, integrity: 66, confidence: 68, fatigue: 49, load: 58, uptime: 90, maintenance_status: 'required', output_quality: 63, risk_level: 'medium', communication_status: 'congested', status: 'maintenance', bandwidth: 56, coordination_efficiency: 61, max_concurrent_tasks: 1, system_health: 62 },
  { bot_id: 'T-304', name: 'Ledger', role: 'task bot', farm_group: 'security-support', specialty: 'verification', level: 5, efficiency: 89, integrity: 93, confidence: 88, fatigue: 19, load: 29, uptime: 98, maintenance_status: 'healthy', output_quality: 90, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 84, coordination_efficiency: 86, max_concurrent_tasks: 2, system_health: 92 },
  { bot_id: 'T-305', name: 'Drift', role: 'task bot', farm_group: 'research', specialty: 'research', level: 4, efficiency: 83, integrity: 84, confidence: 82, fatigue: 35, load: 54, uptime: 96, maintenance_status: 'healthy', output_quality: 78, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 79, coordination_efficiency: 80, max_concurrent_tasks: 1, system_health: 85 },
  { bot_id: 'T-306', name: 'Echo', role: 'task bot', farm_group: 'research', specialty: 'summarization', level: 4, efficiency: 81, integrity: 86, confidence: 79, fatigue: 21, load: 31, uptime: 97, maintenance_status: 'healthy', output_quality: 80, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 77, coordination_efficiency: 79, max_concurrent_tasks: 1, system_health: 86 },
  { bot_id: 'T-307', name: 'Trace', role: 'task bot', farm_group: 'operations', specialty: 'sorting', level: 3, efficiency: 76, integrity: 82, confidence: 74, fatigue: 38, load: 46, uptime: 95, maintenance_status: 'healthy', output_quality: 71, risk_level: 'low', communication_status: 'clear', status: 'assigned', bandwidth: 72, coordination_efficiency: 73, max_concurrent_tasks: 1, system_health: 80 },
  { bot_id: 'T-308', name: 'Beacon', role: 'task bot', farm_group: 'reporting', specialty: 'reporting', level: 4, efficiency: 82, integrity: 88, confidence: 81, fatigue: 27, load: 35, uptime: 97, maintenance_status: 'healthy', output_quality: 81, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 78, coordination_efficiency: 80, max_concurrent_tasks: 1, system_health: 87 },
  { bot_id: 'T-309', name: 'Pulse', role: 'task bot', farm_group: 'monitoring', specialty: 'monitoring', level: 4, efficiency: 85, integrity: 83, confidence: 84, fatigue: 42, load: 71, uptime: 96, maintenance_status: 'scheduled', output_quality: 74, risk_level: 'medium', communication_status: 'delayed', status: 'overloaded', bandwidth: 74, coordination_efficiency: 76, max_concurrent_tasks: 2, system_health: 79 },
  { bot_id: 'T-310', name: 'Vector', role: 'task bot', farm_group: 'monitoring', specialty: 'monitoring', level: 4, efficiency: 80, integrity: 73, confidence: 75, fatigue: 61, load: 81, uptime: 94, maintenance_status: 'scheduled', output_quality: 68, risk_level: 'medium', communication_status: 'delayed', status: 'overloaded', bandwidth: 61, coordination_efficiency: 66, max_concurrent_tasks: 1, system_health: 70 },
  { bot_id: 'T-311', name: 'Delta', role: 'task bot', farm_group: 'operations', specialty: 'analysis', level: 3, efficiency: 78, integrity: 84, confidence: 77, fatigue: 34, load: 44, uptime: 95, maintenance_status: 'healthy', output_quality: 75, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 73, coordination_efficiency: 75, max_concurrent_tasks: 1, system_health: 82 },
  { bot_id: 'T-312', name: 'Quartz', role: 'task bot', farm_group: 'research', specialty: 'research', level: 3, efficiency: 79, integrity: 85, confidence: 78, fatigue: 25, load: 33, uptime: 96, maintenance_status: 'healthy', output_quality: 77, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 74, coordination_efficiency: 77, max_concurrent_tasks: 1, system_health: 84 },
  { bot_id: 'T-313', name: 'Mosaic', role: 'task bot', farm_group: 'support', specialty: 'communications', level: 3, efficiency: 74, integrity: 79, confidence: 72, fatigue: 46, load: 57, uptime: 92, maintenance_status: 'scheduled', output_quality: 69, risk_level: 'medium', communication_status: 'congested', status: 'assigned', bandwidth: 67, coordination_efficiency: 70, max_concurrent_tasks: 1, system_health: 75 },
  { bot_id: 'T-314', name: 'Forge', role: 'task bot', farm_group: 'operations', specialty: 'data_gathering', level: 3, efficiency: 77, integrity: 83, confidence: 75, fatigue: 29, load: 41, uptime: 95, maintenance_status: 'healthy', output_quality: 74, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 72, coordination_efficiency: 74, max_concurrent_tasks: 1, system_health: 82 },
  { bot_id: 'T-315', name: 'Static', role: 'task bot', farm_group: 'security-support', specialty: 'verification', level: 3, efficiency: 76, integrity: 81, confidence: 74, fatigue: 40, load: 48, uptime: 94, maintenance_status: 'healthy', output_quality: 72, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 70, coordination_efficiency: 73, max_concurrent_tasks: 1, system_health: 80 },
  { bot_id: 'T-316', name: 'Node', role: 'task bot', farm_group: 'reporting', specialty: 'reporting', level: 3, efficiency: 78, integrity: 86, confidence: 76, fatigue: 23, load: 30, uptime: 96, maintenance_status: 'healthy', output_quality: 78, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 75, coordination_efficiency: 77, max_concurrent_tasks: 1, system_health: 85 },
  { bot_id: 'T-317', name: 'Cipher', role: 'task bot', farm_group: 'security-support', specialty: 'security', level: 4, efficiency: 82, integrity: 88, confidence: 83, fatigue: 32, load: 45, uptime: 97, maintenance_status: 'healthy', output_quality: 80, risk_level: 'low', communication_status: 'clear', status: 'assigned', bandwidth: 77, coordination_efficiency: 81, max_concurrent_tasks: 1, system_health: 87 },
  { bot_id: 'T-318', name: 'Scope', role: 'task bot', farm_group: 'research', specialty: 'summarization', level: 3, efficiency: 75, integrity: 82, confidence: 73, fatigue: 36, load: 43, uptime: 94, maintenance_status: 'healthy', output_quality: 71, risk_level: 'low', communication_status: 'clear', status: 'active', bandwidth: 71, coordination_efficiency: 74, max_concurrent_tasks: 1, system_health: 80 },
  { bot_id: 'T-319', name: 'Anchor', role: 'task bot', farm_group: 'operations', specialty: 'analysis', level: 4, efficiency: 83, integrity: 87, confidence: 82, fatigue: 30, load: 39, uptime: 97, maintenance_status: 'healthy', output_quality: 81, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 79, coordination_efficiency: 82, max_concurrent_tasks: 1, system_health: 86 },
  { bot_id: 'T-320', name: 'Rook', role: 'task bot', farm_group: 'support', specialty: 'command_support', level: 3, efficiency: 73, integrity: 80, confidence: 72, fatigue: 37, load: 42, uptime: 94, maintenance_status: 'healthy', output_quality: 70, risk_level: 'low', communication_status: 'clear', status: 'idle', bandwidth: 69, coordination_efficiency: 72, max_concurrent_tasks: 1, system_health: 79 }
];

export const DEMO_SQUADS = [
  { name: 'Leader Command', farm_group: 'command', role_type: 'leader', specialization_focus: ['command_support'], coordination_quality: 96, coordination_overhead: 6, reliability_score: 95, throughput_score: 90, current_load: 38, capacity_limit: 120, status: 'active' },
  { name: 'Commander North Wing', farm_group: 'operations', role_type: 'commander', specialization_focus: ['analysis', 'data_gathering', 'sorting'], coordination_quality: 87, coordination_overhead: 12, reliability_score: 86, throughput_score: 83, current_load: 61, capacity_limit: 110, status: 'active' },
  { name: 'Commander Signal Wing', farm_group: 'research', role_type: 'commander', specialization_focus: ['research', 'summarization', 'reporting'], coordination_quality: 86, coordination_overhead: 13, reliability_score: 85, throughput_score: 81, current_load: 58, capacity_limit: 110, status: 'active' },
  { name: 'Security Oversight', farm_group: 'security', role_type: 'security', specialization_focus: ['security', 'verification', 'monitoring'], coordination_quality: 88, coordination_overhead: 10, reliability_score: 92, throughput_score: 76, current_load: 35, capacity_limit: 80, status: 'active' },
  { name: 'Operations Squad Alpha', farm_group: 'operations', role_type: 'task', specialization_focus: ['data_gathering', 'analysis', 'sorting'], coordination_quality: 80, coordination_overhead: 18, reliability_score: 79, throughput_score: 77, current_load: 74, capacity_limit: 100, status: 'active' },
  { name: 'Research Squad Beta', farm_group: 'research', role_type: 'task', specialization_focus: ['research', 'summarization', 'reporting'], coordination_quality: 79, coordination_overhead: 17, reliability_score: 80, throughput_score: 76, current_load: 69, capacity_limit: 100, status: 'active' },
  { name: 'Support Squad Gamma', farm_group: 'support', role_type: 'task', specialization_focus: ['communications', 'command_support', 'reporting'], coordination_quality: 72, coordination_overhead: 20, reliability_score: 70, throughput_score: 68, current_load: 63, capacity_limit: 92, status: 'strained' },
  { name: 'Monitoring Squad Delta', farm_group: 'monitoring', role_type: 'task', specialization_focus: ['monitoring', 'verification', 'security'], coordination_quality: 74, coordination_overhead: 19, reliability_score: 72, throughput_score: 69, current_load: 77, capacity_limit: 95, status: 'strained' }
];

export const DEMO_MISSIONS = [
  { title: 'Anomaly command sweep', objective: 'Detect pricing anomalies, verify contradictions, and produce a trusted alert package.', status: 'active', priority: 'high', progress: 58, mission_value: 180, coordination_complexity: 61, security_pressure: 36, expected_output_quality: 84, actual_output_quality: 77, success_probability: 74 },
  { title: 'Backlog compression cycle', objective: 'Reduce pending queue depth across research, support, and reporting lanes.', status: 'active', priority: 'medium', progress: 41, mission_value: 130, coordination_complexity: 47, security_pressure: 18, expected_output_quality: 79, actual_output_quality: 72, success_probability: 76 },
  { title: 'Integrity stabilization program', objective: 'Repair unstable communications and quarantine contradiction-prone units before next cycle.', status: 'review', priority: 'high', progress: 33, mission_value: 150, coordination_complexity: 52, security_pressure: 64, expected_output_quality: 82, actual_output_quality: 69, success_probability: 61 }
];

export const DEMO_TASKS = [
  { title: 'Gather venue spread snapshots', description: 'Collect spread snapshots from priority markets.', work_type: 'data_gathering', required_specialization: 'data_gathering', priority: 'high', status: 'active', urgency: 82, risk: 25, expected_output_value: 84, bot_fit_score: 89, coordination_cost: 10, queue_bucket: 'operations', estimated_load: 32, progress: 70 },
  { title: 'Detect contradiction clusters', description: 'Check monitoring outputs for cross-stream contradictions.', work_type: 'verification', required_specialization: 'verification', priority: 'critical', status: 'review', urgency: 93, risk: 72, expected_output_value: 93, bot_fit_score: 86, coordination_cost: 14, queue_bucket: 'security', estimated_load: 38, progress: 55 },
  { title: 'Summarize overnight logs', description: 'Prepare a concise mission summary for command.', work_type: 'reporting', required_specialization: 'reporting', priority: 'medium', status: 'pending', urgency: 57, risk: 16, expected_output_value: 58, bot_fit_score: 74, coordination_cost: 8, queue_bucket: 'reporting', estimated_load: 16, progress: 0 },
  { title: 'Sort support escalation queue', description: 'Rank support tickets by urgency and operational value.', work_type: 'sorting', required_specialization: 'sorting', priority: 'medium', status: 'assigned', urgency: 66, risk: 18, expected_output_value: 52, bot_fit_score: 77, coordination_cost: 7, queue_bucket: 'support', estimated_load: 20, progress: 28 },
  { title: 'Research signal brief', description: 'Compile a short research brief on current anomaly themes.', work_type: 'research', required_specialization: 'research', priority: 'high', status: 'assigned', urgency: 74, risk: 22, expected_output_value: 73, bot_fit_score: 83, coordination_cost: 11, queue_bucket: 'research', estimated_load: 24, progress: 22 },
  { title: 'Repair communication drift', description: 'Stabilize congested communication chains in support squads.', work_type: 'communications', required_specialization: 'communications', priority: 'high', status: 'blocked', urgency: 79, risk: 49, expected_output_value: 67, bot_fit_score: 71, coordination_cost: 15, queue_bucket: 'support', estimated_load: 29, progress: 18, blocked_reason: 'Relay path integrity unstable' },
  { title: 'Monitor queue saturation', description: 'Watch task queues for overload spikes and recommend rebalancing.', work_type: 'monitoring', required_specialization: 'monitoring', priority: 'high', status: 'active', urgency: 76, risk: 41, expected_output_value: 71, bot_fit_score: 82, coordination_cost: 10, queue_bucket: 'operations', estimated_load: 26, progress: 64 },
  { title: 'Command support summary', description: 'Merge commander updates into a farm-level view.', work_type: 'command_support', required_specialization: 'command_support', priority: 'medium', status: 'pending', urgency: 51, risk: 12, expected_output_value: 47, bot_fit_score: 69, coordination_cost: 9, queue_bucket: 'reporting', estimated_load: 14, progress: 0 }
];

export const DEMO_OUTPUTS = [
  { output_type: 'processed_intelligence', assignment_quality: 88, specialization_fit: 91, load_penalty: 9, coordination_penalty: 6, quality_score: 84, value_score: 86, summary: 'Prism produced a high-signal anomaly packet after a strong specialty match and low coordination loss.' },
  { output_type: 'report', assignment_quality: 76, specialization_fit: 82, load_penalty: 11, coordination_penalty: 8, quality_score: 73, value_score: 64, summary: 'Beacon generated a useful but compressed overnight report under moderate queue pressure.' },
  { output_type: 'alert', assignment_quality: 83, specialization_fit: 79, load_penalty: 18, coordination_penalty: 12, quality_score: 69, value_score: 78, summary: 'Vector triggered an alert, but overload reduced confidence and forced security review.' }
];

export const DEMO_RISKS = [
  { flag_type: 'integrity_drop', severity: 'warning', status: 'open', details: 'Relay integrity is below stable range after repeated congested communication cycles.' },
  { flag_type: 'low_confidence', severity: 'warning', status: 'reviewing', details: 'Vector is producing lower-confidence monitoring judgments under overload.' },
  { flag_type: 'contradiction', severity: 'critical', status: 'open', details: 'Verification stream found contradiction clusters requiring quarantine review.' },
  { flag_type: 'poor_assignment', severity: 'warning', status: 'open', details: 'One reporting task is assigned to a support-biased path, reducing likely output quality.' }
];

export const DEMO_UPGRADES = [
  { name: 'Queue Throughput Bus', upgrade_type: 'capacity', level: 2, effect_value: 10, complexity_cost: 3, applied_to: 'farm' },
  { name: 'Verification Matrix', upgrade_type: 'verification_quality', level: 1, effect_value: 8, complexity_cost: 2, applied_to: 'squad' },
  { name: 'Fatigue Dampener', upgrade_type: 'fatigue_reduction', level: 1, effect_value: 7, complexity_cost: 2, applied_to: 'farm' },
  { name: 'Coordination Mesh', upgrade_type: 'coordination', level: 1, effect_value: 6, complexity_cost: 4, applied_to: 'farm' }
];

export const DEMO_ACTIVITY = [
  { actor_type: 'farm', event_type: 'queue_rebalanced', summary: 'Operations queue was rebalanced after overload threshold triggered in monitoring lanes.', impact_score: 11 },
  { actor_type: 'bot', event_type: 'maintenance_started', summary: 'Relay entered maintenance after sustained communication congestion.', impact_score: -6 },
  { actor_type: 'system', event_type: 'upgrade_applied', summary: 'Queue Throughput Bus expanded queue capacity but raised coordination complexity.', impact_score: 14 }
];

export const DEMO_MAINTENANCE = [
  { maintenance_type: 'repair', status: 'in_progress', impact: 'Repairing unstable communications path.', recovery_gain: 18 },
  { maintenance_type: 'rest', status: 'complete', impact: 'Fatigue reduced after recovery cycle.', recovery_gain: 24 }
];